spring:
  application:
    name: AUTH-SERVICE
  config:
    import:
      - optional:file:../FinFlow_Config_Server/application.yml
      - optional:file:../FinFlow_Config_Server/AUTH-SERVICE.yml
      - optional:file:./FinFlow_Config_Server/application.yml
      - optional:file:./FinFlow_Config_Server/AUTH-SERVICE.yml
      - optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
  cloud:
    config:
      label: ${CONFIG_REPO_LABEL:main}
