server:
  port: 9000

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

application:
  security:
    jwt:
      secret: ${JWT_SECRET:ThisIsADevelopmentOnlyJwtSecretKeyForFinFlowAuthService123456789}

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.cloud.gateway: DEBUG
