server:
  port: ${SERVER_PORT:8888}

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_REPO_URI:file:../FinFlow_Config_Server}
          default-label: ${CONFIG_REPO_LABEL:main}
          clone-on-start: true
          force-pull: true
          timeout: 15

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT:http://localhost:9411/api/v2/spans}
  endpoints:
    web:
      exposure:
        include: health,info,env
  endpoint:
    health:
      show-details: always
