spring:
  application:
    name: ADMIN-SERVICE
  config:
    import: "configserver:${CONFIG_SERVER_URL:http://localhost:8888}"
  cloud:
    config:
      enabled: ${CONFIG_SERVER_ENABLED:true}
      uri: ${CONFIG_SERVER_URL:http://localhost:8888}
      label: ${CONFIG_REPO_LABEL:main}
      fail-fast: true
