server:
  port: 8081

spring:
  application:
    name: ADMIN-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/admindb
    username: root
    password: ${DB_PASSWORD:273031}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

application:
  security:
    jwt:
      secret: ${JWT_SECRET:ThisIsADevelopmentOnlyJwtSecretKeyForFinFlowAuthService123456789}

springdoc:
  api-docs:
    path: /admin/v3/api-docs
  swagger-ui:
    path: /swagger-ui.html