server:
  port: ${SERVER_PORT:8083}

spring:
  application:
    name: DOCUMENT-SERVICE

  datasource:
    url: jdbc:mysql://${DB_HOST:127.0.0.1}:${DB_PORT:3306}/${DB_NAME:documentdb}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:273031}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

file:
  upload-dir: uploads/

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

application:
  security:
    jwt:
      secret: ${JWT_SECRET:ThisIsADevelopmentOnlyJwtSecretKeyForFinFlowAuthService123456789}
springdoc:
  api-docs:
    path: /documents/v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
