server.port=8083

spring.datasource.url=jdbc:mysql://localhost:3306/documentdb
spring.datasource.username=root
spring.datasource.password=273031

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

file.upload-dir=uploads/