server:
  port: 8083

spring:
  application:
    name: DOCUMENT-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/documentdb
    username: root
    password: 273031

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

file:
  upload-dir: uploads/

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
