spring:
  application:
    name: EUREKA-SERVER
  config:
    import:
      - optional:file:../FinFlow_Config_Server/application.yml
      - optional:file:../FinFlow_Config_Server/EUREKA-SERVER.yml
      - optional:file:./FinFlow_Config_Server/application.yml
      - optional:file:./FinFlow_Config_Server/EUREKA-SERVER.yml
      - optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
  cloud:
    config:
      label: ${CONFIG_REPO_LABEL:main}
